#!/bin/sh

# Prints the current volume or 🔇 if muted.

case $BLOCK_BUTTON in
	1) setsid -f "$TERMINAL" -e pulsemixer ;;
	2) pamixer -t ;;
	4) pamixer --allow-boost -i 1 ;;
	5) pamixer --allow-boost -d 1 ;;
	3) notify-send "醙 Volume module" "\- Shows volume 墳, 婢 if muted.
- Middle click to mute.
- Scroll to change." ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

vol="$(pamixer --get-volume)"

[ $(pamixer --get-mute) = true ] && echo [ 婢 $vol% ] && exit

if [ "$vol" -gt "60" ]; then
	icon="墳"
elif [ "$vol" -gt "30" ]; then
	icon="奔"
elif [ "$vol" -gt "0" ]; then
	icon="奄"
else
	icon="婢"
fi

echo "[ $icon $vol% ]"
