#!/bin/bash

if [[ $# -eq 0 ]]; then
    echo 'No arguments supplied'
    exit 1
fi

if [[ $1 -gt 0 ]]; then
  pamixer -i $1
fi

if [[ $1 -lt 0 ]]; then
  pamixer -d $(($1 * -1))
fi

if [[ $1 == 'm' ]]; then
  pamixer -t
fi

vol=$(pamixer --get-volume)
progress_bar="-h string:hlcolor:#f0f0f0 -h int:value:$vol"

if [[ "$vol" -gt "60" ]]; then
    icon='-i audio-volume-high'
elif [[ "$vol" -gt "30" ]]; then 
    icon='-i audio-volume-medium'
elif [[ "$vol" -gt "0" ]]; then 
    icon='-i audio-volume-low'
fi

if [[ "$vol" -eq "0" ]] || [[ $(pamixer --get-mute) = true ]]; then 
    icon='-i audio-volume-muted'
fi

notify-send -u low $icon $progress_bar -t 1300 "VOLUME"
