#!/bin/sh

if [ -z "$1" ]; then
	echo "Please select a wallpaper"
	exit 1
fi

wallpaper=$(realpath $1)

function select_screen() {
	local monitor="$(xrandr --listactivemonitors | sed 1d | awk '{print NR,$4}' | dmenu -i -p 'Screen: ' | awk '{print $1 - 1}')"

	echo $monitor
}

screen=$(select_screen)

nitrogen --set-scaled $wallpaper --head=$screen --save

function change_colorscheme() {
	wal -i $wallpaper -n
	pywalfox update

	notify-send "Colorscheme" "Recompiling dwm, dmenu and st with new colorscheme..."

	local src_dir="$HOME/source"

	(cd $src_dir/dwm && make clean install >/dev/null)
	(cd $src_dir/dmenu && make clean install >/dev/null)
	(cd $src_dir/st && make clean install >/dev/null)

}

case "$(printf 'Yes\nNo' | dmenu -i -p 'Change colorscheme')" in
'Yes') change_colorscheme ;;
*) exit 1 ;;
esac
