#!/bin/python3

import os
import pathlib
from colorama import Fore, Style

HOME = os.environ['HOME']
PATH_WALLPAPERS = os.path.join(HOME, 'imgs', 'wallpapers')

wallpapers_dir = os.listdir(PATH_WALLPAPERS)

for cur_dir in wallpapers_dir:
    cur_wallpaper_dir = os.path.join(PATH_WALLPAPERS, cur_dir)
    wallpapers = os.listdir(cur_wallpaper_dir)
    wallpapers.sort()

    for index, img_name in enumerate(wallpapers):
        if cur_dir in img_name:
            continue

        target_img = os.path.join(cur_wallpaper_dir, img_name)
        file_exention = pathlib.Path(img_name).suffix
        new_name = os.path.join(
            cur_wallpaper_dir, f'{index}-{cur_dir}{file_exention}')
        print(f'{Fore.RED}{Style.BRIGHT}Renamed file: {target_img}{Style.RESET_ALL}')
        print(f'{Fore.GREEN}{Style.BRIGHT}New name: {new_name}{Style.RESET_ALL}\n')
        os.rename(src=target_img, dst=new_name)
